apiVersion: v1
kind: ResourceQuota  # kind is used to specific the kubernetes object being references by the manifest 
metadata:
  name: dev-resource-quota
  namespace: dev
spec:
  hard:
    pods: "5000"
    requests.cpu: "100"
    requests.memory: "500Gi"
    limits.cpu: "100"
    limits.memory: "500Gi"
